- name: Base setup for all devices
  hosts: all
  roles:
    - todo

- name: Special stuff for private devices only
  hosts:
    - private-laptop
  roles:
    - todo

    - name: Special stuff for work - employe devices only
  hosts:
    - work-laptop
  roles:
    - todo

