---
  - name: Ensure directories
    become: yes
    file:
      path: /etc/systemd/system/getty@.service.d
      state: directory

  - name: Activate numlock on boot
    become: yes
    copy:
      src: files/activate-numlock.conf
      dest: /etc/systemd/system/getty@.service.d/activate-numlock.conf
