---
- name: Clone the Devicons Repo
  git:
    repo: https://github.com/alexanderjeurissen/ranger_devicons
    dest: /home/{{ user_name }}/.cache/ranger_devicons
  tags:
    - ranger
    - ranger:plugin
    - ranger:plugin:devicons

- name: Install Devicons
  make:
    chdir: /home/{{ user_name }}/.cache/ranger_devicons
    target: install
  tags:
    - ranger
    - ranger:plugin
    - ranger:plugin:devicons
