---
  - name: Install OpenSSH
    become: yes
    package:
      name: openssh
      state: present

  - name: Copy ssh config and keys
    copy:
      src: "files/{{ item }}"
      dest: "/home/{{ user_name }}/.ssh/{{ item }}"
      owner: "{{ user_name }}"
      group: "{{ user_group }}"
      mode: "u=rw,g=,o="
    with_items:
      - config
      - flying-laptop_rsa
      - github_id_rsa
