---
  - name: Install Brave browser
    become: yes
    shell: pikaur -Sy --noconfirm brave-bin
    tags:
      - browser:brave

  - name: Enable sandboxing
    become: yes
    copy:
      src: files/unprivileged_userns_clone.conf
      dest: /etc/sysctl.d/unprivileged_userns_clone.conf
    tags:
      - browser:brave
      - kernelparameter

  - name: Link App shortcuts
    become: yes
    file:
      state: link
      src: "{{ dotfiles_path }}/brave/{{ item }}"
      dest: "/usr/local/bin/{{ item }}"
    with_items:
      - meistertask
    tags:
      - browser:brave
      - applinks
