---
  - name: Install rofi
    become: yes
    package:
      name: rofi
      state: present
    tags:
      - rofi

  - name: Ensure config directory
    file:
      state: directory
      path: "/home/{{ user_name }}/.config/rofi"
    tags:
      - rofi:config

  - name: Link config
    become: yes
    file:
      state: link
      src: "{{ dotfiles_path }}/rofi/rofi.conf"
      dest: "/home/{{ user_name }}/.config/rofi/config"
    tags:
      - rofi:config

  - name: Link helper scripts and custom modi
    become: yes
    file:
      state: link
      src: "{{ dotfiles_path }}/rofi/scripts/{{ item }}"
      dest: "/usr/local/bin/rofi-{{ item }}"
      mode: "u=rx,g=rx,o=rx"
    with_items:
      - network-select.sh
    tags:
      - rofi:scripts
