---
  - name: Install docker
    become: yes
    package:
      name: docker
      state: present
    tags:
      - docker

  - name: Enable and start docker service
    become: yes
    service:
      name: docker
      enabled: yes
      state: started
    tags:
      - docker

  - name: Add me to the docker group so no sudo is needed
    become: yes
    user:
      name: "{{ user_name }}"
      groups: docker
      append: yes
    tags:
      - docker
