- name: Fontmanager > Get sources
  become: yes
  git:
    repo: 'https://github.com/FontManager/master.git'
    dest: '/usr/src/fontmanager'
  tags:
    - fonts:fontmanager

- name: Fontmanager > Installing dependencies
  become: yes
  package:
    name: '{{ item }}'
    state: present
  with_items:
    - libgee
  tags:
    - fonts:fontmanager

- name: Fontmanager > Autoconf
  become: yes
  command: ./autogen.sh
  args:
    chdir: '/usr/src/fontmanager'
  tags:
    - fonts:fontmanager

- name: Fontmanager > Configure make environment
  become: yes
  command: ./configure
  args:
    chdir: '/usr/src/fontmanager'
  tags:
    - fonts:fontmanager

- name: Fontmanager > Build
  become: yes
  make:
    chdir: '/usr/src/fontmanager'
  tags:
    - fonts:fontmanager

- name: Fontmanager > Install
  become: yes
  make:
    target: install
    chdir: '/usr/src/fontmanager'
  tags:
    - fonts:fontmanager
