---
  - name: Install some default fonts
    become: yes
    pacman:
      name: [ terminus-font, ttf-dejavu, noto-fonts, noto-fonts-emoji, ttf-liberation, ttf-freefont, ttf-freefont ]
      state: present
      update_cache: yes
    tags:
      - fonts

  - name: Install some additional fonts from the AUR
    become: yes
    shell: "pikaur -Sy --noconfirm {{ item }}"
    with_items:
      - nerd-fonts-source-code-pro
      #- nerd-fonts-complete # very big package
    tags:
      - fonts
    
